# Generated by Django 4.2.17 on 2024-12-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_choice',
            field=models.IntegerField(default=0),
        ),
    ]
